# Generated by Django 3.1 on 2020-08-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course_Number', models.IntegerField(default='')),
                ('Instructor_Name', models.CharField(max_length=60)),
                ('Duration', models.FloatField(max_length=60)),
            ],
        ),
    ]
